export const CollectionHtml = [
  {
    src: '/image/1.jpg',
    title: '美麗華新麗華',
    descript: 'Company',
    link: 'https://www.beautybuild.com.tw/',
  },
  {
    src: '/image/2.jpg',
    title: '駥陞牧業',
    descript: 'Company',
    link: '',
  },
  {
    src: '/image/3.jpg',
    title: '天際Skyline',
    descript: 'Real Estate',
    link: 'http://skyline.victo.com.tw/',
  },
  {
    src: '/image/4.jpg',
    title: '幸福時光',
    descript: 'Real Estate',
    link: '',
  },
  {
    src: '/image/5.jpg',
    title: '勤樸建設',
    descript: 'Company',
    link: '',
  },
  {
    src: '/image/6.jpg',
    title: '米築',
    descript: 'Real Estate Platform',
    link: 'http://www.maisonbest.com.tw/',
  },
  {
    src: '/image/7.jpg',
    title: '笠竹園',
    descript: 'Restaurant',
    link: '',
  },
  {
    src: '/image/8.jpg',
    title: '南興米粉',
    descript: 'Company, E-commerce',
    link: 'http://www.nsfood.com.tw/',
  },
  {
    src: '/image/9.jpg',
    title: '義翰',
    descript: 'Company',
    link: '',
  },
  {
    src: '/image/10.jpg',
    title: '早安國揚',
    descript: 'Real Estate',
    link: '',
  },
  {
    src: '/image/11.jpg',
    title: 'GillyGo',
    descript: 'Customized，Laravel',
    link: '',
  },
  {
    src: '/image/12.jpg',
    title: '建祥營建企業團',
    descript: 'Company',
    link: '',
  },
  {
    src: '/image/13.jpg',
    title: '實德璞園',
    descript: 'Real Estate',
    link: 'https://project.pyct.com.tw/hot100/',
  },
  {
    src: '/image/14.jpg',
    title: '日勝幸福站',
    descript: 'Social Housing',
    link: 'http://www.perfectlife.com.tw/index',
  },
  {
    src: '/image/15.jpg',
    title: '創緯建設',
    descript: 'Company',
    link: '',
  },
  {
    src: '/image/16.jpg',
    title: '創薪建設',
    descript: 'Company',
    link: '',
  },
  {
    src: '/image/17.jpg',
    title: '創翼建築設計事務所',
    descript: 'Company',
    link: '',
  },
  {
    src: '/image/18.jpg',
    title: '甲桂林',
    descript: 'Company',
    link: 'http://topscene.com.tw/',
  },
  {
    src: '/image/19.jpg',
    title: '勵傑國際智慧財產權事務所',
    descript: 'Office',
    link: '',
  },
  {
    src: '/image/20.jpg',
    title: '寶灝工作團隊',
    descript: 'Customized. Laravel',
    link: '',
  },
  {
    src: '/image/21.jpg',
    title: 'No2cafe',
    descript: 'Restaurant',
    link: '',
  },
  {
    src: '/image/22.jpg',
    title: 'Pratice in 2017',
    descript: '',
    link: 'https://sawachika.github.io/Collections-2017/',
  },
].reverse()

export const CollectionVue = [
  // {
  //   src: '/image/v7.jpg',
  //   title: '女王電波',
  //   descript: 'One page ad',
  //   link: 'https://event.intone.cc/endymed/',
  // },
  {
    src: '/image/v11.jpg',
    title: 'Nuxt2-Template',
    descript: 'Multi language RWD template，Bootstrap-Vue V2，Bootstrap 4',
    link: 'https://sawachika.github.io/Nuxt2-Template/',
  },
  {
    src: '/image/v12.jpg',
    title: 'Nuxt3-Template-Image',
    descript: 'Starter template, Pug + UnoCSS + Stylus + TS',
    link: 'https://github.com/Sawachika/Nuxt3-Template-Image',
  },
  {
    src: '/image/v10.jpg',
    title: 'Nuxt3-Template-Video',
    descript: 'RWD template，which serves as a basis for customizing multiple websites.',
    link: 'https://sawachika.github.io/Nuxt3-Template-Video/',
  },
  {
    src: '/image/v8.jpg',
    title: 'Vitart Digital Art',
    descript: 'Nuxt3 RWD E-commerce website. Art trading platform',
    link: 'https://www.pmivitart.com/',
  },
].reverse()